security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo+pMOAq3ZeuzL6Yu8OEA
          7hbaJFm1rrOVkTcZzO7N5yLoT2RHgVEpm3AfrvMt6gQ7nHBw9Y1MSFNNz0TTxHsh
          f17/Rj64Uvw6DCoW1kSs+CbBqmIvYHp13idhFIZjodNDsIGX3yqGb2ZF92YDHvGE
          LnjuyMFJygeGyxv+iOXOyAoUxSQ25nbveYeUHTZ6ORG9Q5Cr0szJ+b1JBY0uj5bb
          9FjggHlOdibrXE38UnDgBuQRoHTG5LMhZ3SY+Ei+Pb9pouQ6b7yygXzPaY2w5yQl
          HHTzA9oMUGVsM5OZlU16kG6n6oz9CEC4XKcZN2rzYGk38y/NKbS5kjsLRCFTiF/p
          2wIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource

logging:
  level:
    ninja.goofyahead.main.interceptor.ImpersonateInterceptor : DEBUG